sonar.projectKey=php-symfony-ci-demo
sonar.projectName=PHP Symfony CI Demo
sonar.sources=src
sonar.tests=tests
sonar.php.tests.reportPath=var/junit.xml
sonar.php.coverage.reportPaths=var/coverage.xml
sonar.sourceEncoding=UTF-8
